# Generated by Django 6.1.1 on 2026-09-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_author_options_alter_blog_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='socialaccounts',
            options={'verbose_name_plural': 'Socialaccounts'},
        ),
    ]
